//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsPatchInstallerUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsPatchInstallerUI.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed.
        /// </summary>
        internal static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Name and SSO.
        /// </summary>
        internal static string NameWarning {
            get {
                return ResourceManager.GetString("NameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field Empty Error.
        /// </summary>
        internal static string NameWarningCaption {
            get {
                return ResourceManager.GetString("NameWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the cab file &amp; start to proceed..
        /// </summary>
        internal static string ProgressBarMessage {
            get {
                return ResourceManager.GetString("ProgressBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Existing Windows Patches..
        /// </summary>
        internal static string ProgressBarMessage1 {
            get {
                return ResourceManager.GetString("ProgressBarMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Patch Installation.
        /// </summary>
        internal static string ProgressBarMessage2 {
            get {
                return ResourceManager.GetString("ProgressBarMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing List of Patches to be Installed..
        /// </summary>
        internal static string ProgressBarMessage3 {
            get {
                return ResourceManager.GetString("ProgressBarMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking New Installed Patches..
        /// </summary>
        internal static string ProgressBarMessage4 {
            get {
                return ResourceManager.GetString("ProgressBarMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Patch Installation Report..
        /// </summary>
        internal static string ProgressBarMessage5 {
            get {
                return ResourceManager.GetString("ProgressBarMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch Installation Complete..
        /// </summary>
        internal static string ProgressBarMessage6 {
            get {
                return ResourceManager.GetString("ProgressBarMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Patches....
        /// </summary>
        internal static string ProgressBarMessage7 {
            get {
                return ResourceManager.GetString("ProgressBarMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting the report and finalizing..
        /// </summary>
        internal static string ProgressBarMessage8 {
            get {
                return ResourceManager.GetString("ProgressBarMessage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select cab file first by clicking browse button..
        /// </summary>
        internal static string SelectCabFile {
            get {
                return ResourceManager.GetString("SelectCabFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Selected Error.
        /// </summary>
        internal static string SelectCabFileCaption {
            get {
                return ResourceManager.GetString("SelectCabFileCaption", resourceCulture);
            }
        }
    }
}
